// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-Mh3sFDPEwOFYYAaAG-NRnNMMLzoaTac',
    appId: '1:1019181902979:web:49d0f3db11071f7a15ffb6',
    messagingSenderId: '1019181902979',
    projectId: 'chatapp-flutter-pr',
    authDomain: 'chatapp-flutter-pr.firebaseapp.com',
    storageBucket: 'chatapp-flutter-pr.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgqfrXqE1g1_DoTEKbUt5UvORZaN0_JEg',
    appId: '1:1019181902979:android:ef130bd144243f2615ffb6',
    messagingSenderId: '1019181902979',
    projectId: 'chatapp-flutter-pr',
    storageBucket: 'chatapp-flutter-pr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDebOFfg_7RlGOLHeQuApaT0kuZY6IpGmc',
    appId: '1:1019181902979:ios:dcdb23d85807387a15ffb6',
    messagingSenderId: '1019181902979',
    projectId: 'chatapp-flutter-pr',
    storageBucket: 'chatapp-flutter-pr.appspot.com',
    iosBundleId: 'com.chatapp.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDebOFfg_7RlGOLHeQuApaT0kuZY6IpGmc',
    appId: '1:1019181902979:ios:dcdb23d85807387a15ffb6',
    messagingSenderId: '1019181902979',
    projectId: 'chatapp-flutter-pr',
    storageBucket: 'chatapp-flutter-pr.appspot.com',
    iosBundleId: 'com.chatapp.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-Mh3sFDPEwOFYYAaAG-NRnNMMLzoaTac',
    appId: '1:1019181902979:web:061fd74d0a490bc215ffb6',
    messagingSenderId: '1019181902979',
    projectId: 'chatapp-flutter-pr',
    authDomain: 'chatapp-flutter-pr.firebaseapp.com',
    storageBucket: 'chatapp-flutter-pr.appspot.com',
  );
}
